import { Metadata } from "next";

import { LinkButton } from "@/app/_lib/buttons";
import "./globals.css";

export const metadata: Metadata = {
	title: {
		absolute: "",
		default: "Next JS Tutorial",
		template: "%s Tutorial",
	},
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
					<LinkButton>
						<p>Home</p>
					</LinkButton>
				</header>
				{children}
				<footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
